// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iTec_project.DataBase;

#nullable disable

namespace iTec_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230401122918_update1")]
    partial class update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iTec_project.Features.Profiles.Models.ProfileModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int[]>("BackendFramework")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int[]>("BackendFrameworkTools")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int[]>("CommunicationSkillsRating")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("ComunicationStyle")
                        .HasColumnType("integer");

                    b.Property<int>("ConflictsHandle")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DevPost")
                        .HasColumnType("integer");

                    b.Property<int[]>("FrameworkExperience")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int[]>("FrontendFramework")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int[]>("FrontendFrameworkTools")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int[]>("IndustriesWorkExperience")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("OtherBackendFrameworkOption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherComunicationStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherConflictsHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherFrontendFrameworkOption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherOption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProgramingLanguages")
                        .HasColumnType("integer");

                    b.Property<int[]>("TeamWorkAbilityRate")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("User_id")
                        .HasColumnType("text");

                    b.Property<int[]>("WorkExperience")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("iTec_project.Features.Roles.Models.RoleModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("iTec_project.Features.Users.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profile_id")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Profile_id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("iTec_project.Features.Profiles.Models.ProfileModel", b =>
                {
                    b.HasOne("iTec_project.Features.Users.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("User_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iTec_project.Features.Users.Models.UserModel", b =>
                {
                    b.HasOne("iTec_project.Features.Profiles.Models.ProfileModel", "Profile")
                        .WithMany()
                        .HasForeignKey("Profile_id");

                    b.HasOne("iTec_project.Features.Roles.Models.RoleModel", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
